/*
 * ADC_int.h
 *
 *  Created on: Feb 17, 2023
 *      Author: top
 */

#ifndef ADC_INTERFACE_H_
#define ADC_INTERFACE_H_

//ES_t ADC_enuInit(void);
//u16 ADC_u16GetChannelReading(u8 Copy_u8ChannelNumber);



/*Options of Analog Channel and Gain Selection */

#define ADC_SINGLE_ENDED_INPUT_ADC0_CH0                            0
#define ADC_SINGLE_ENDED_INPUT_ADC1_CH1                            1
#define ADC_SINGLE_ENDED_INPUT_ADC2_CH2                            2
#define ADC_SINGLE_ENDED_INPUT_ADC3_CH3                            3
#define ADC_SINGLE_ENDED_INPUT_ADC4_CH4                            4
#define ADC_SINGLE_ENDED_INPUT_ADC5_CH5                            5
#define ADC_SINGLE_ENDED_INPUT_ADC6_CH6                            6
#define ADC_SINGLE_ENDED_INPUT_ADC7_CH7                            7
#define ADC_DIFFERENTIAL_INPUT_POADC0_NEADC0_GAIN10_CH8            8
#define ADC_DIFFERENTIAL_INPUT_POADC1_NEADC0_GAIN10_CH9            9
#define ADC_DIFFERENTIAL_INPUT_POADC0_NEADC0_GAIN200_CH10          10
#define ADC_DIFFERENTIAL_INPUT_POADC1_NEADC0_GAIN200_CH11          11
#define ADC_DIFFERENTIAL_INPUT_POADC2_NEADC2_GAIN10_CH12           12
#define ADC_DIFFERENTIAL_INPUT_POADC3_NEADC2_GAIN10_CH13           13
#define ADC_DIFFERENTIAL_INPUT_POADC2_NEADC2_GAIN200_CH14          14
#define ADC_DIFFERENTIAL_INPUT_POADC3_NEADC2_GAIN200_CH15          15
#define ADC_DIFFERENTIAL_INPUT_POADC0_NEADC1_NOGAIN_CH16           16
#define ADC_DIFFERENTIAL_INPUT_POADC1_NEADC1_NOGAIN_CH17           17
#define ADC_DIFFERENTIAL_INPUT_POADC2_NEADC1_NOGAIN_CH18           18
#define ADC_DIFFERENTIAL_INPUT_POADC3_NEADC1_NOGAIN_CH19           19
#define ADC_DIFFERENTIAL_INPUT_POADC4_NEADC1_NOGAIN_CH20           20
#define ADC_DIFFERENTIAL_INPUT_POADC5_NEADC1_NOGAIN_CH21           21
#define ADC_DIFFERENTIAL_INPUT_POADC6_NEADC1_NOGAIN_CH22           22
#define ADC_DIFFERENTIAL_INPUT_POADC7_NEADC1_NOGAIN_CH23           23
#define ADC_DIFFERENTIAL_INPUT_POADC0_NEADC2_NOGAIN_CH24           24
#define ADC_DIFFERENTIAL_INPUT_POADC1_NEADC2_NOGAIN_CH25           25
#define ADC_DIFFERENTIAL_INPUT_POADC2_NEADC2_NOGAIN_CH26           26
#define ADC_DIFFERENTIAL_INPUT_POADC3_NEADC2_NOGAIN_CH27           27
#define ADC_DIFFERENTIAL_INPUT_POADC4_NEADC2_NOGAIN_CH28           28
#define ADC_DIFFERENTIAL_INPUT_POADC5_NEADC2_NOGAIN_CH29           29
#define ADC_SINGLE_INDED_INPUT_CONSTANT_VOLTAGE                    30
#define ADC_SINGLE_INDED_INPUT_GROUND                              31



#endif /* ADC_INTERFACE_H_ */
